### ISSUE TITLE
Web container broken

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#2386]
Keeps on saying this on next:

```
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
error - Failed to load next.config.js, see more info here https://nextjs.org/docs/messages/next-config-error
Error: Cannot find module './i18n/namespaces'
Require stack:
- /app/next-i18next.config.js
- /app/next.config.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.mod._resolveFilename (/app/node_modules/next/dist/build/webpack/require-hook.js:171:28)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/app/next-i18next.config.js:2:24)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/app/next-i18next.config.js', '/app/next.config.js' ]
}
```

**Comment by aapeliv** [comment]
Fixed in 5e9f2b6ad5cd6cba462d15c21cf3dff50b789f62
