### ISSUE TITLE
Web container issue

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/couchers#2625]
The container isn't starting up and is giving a 500, here are logs from next:

```
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from /app/.env.production                                                                                                 
warn  - using beta Middleware (not covered by semver) - https://nextjs.org/docs/messages/beta-middleware
Error: URLs is malformed. Please use only absolute URLs - https://nextjs.org/docs/messages/middleware-relative-urls
    at Object.validateURL (/app/.next/server/pages/_middleware.js:3065:15)
    at Function.rewrite (/app/.next/server/pages/_middleware.js:2908:53)                      
    ... 4 lines matching cause stack trace ...                                                                                               
    at NextNodeServer.runMiddleware (/app/node_modules/next/dist/server/next-server.js:842:46)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)          
    at async Object.fn (/app/node_modules/next/dist/server/next-server.js:691:30)
    at async Router.execute (/app/node_modules/next/dist/server/router.js:228:32) {
  [cause]: TypeError [ERR_INVALID_URL]: Invalid URL
      at new NodeError (node:internal/errors:372:5)
      at onParseError (node:internal/url:563:9)                                                                                              
      at new URL (node:internal/url:643:5)                                                                                                   
      at Object.validateURL (/app/.next/server/pages/_middleware.js:3063:23)            
      at Function.rewrite (/app/.next/server/pages/_middleware.js:2908:53)
      at Object.middleware [as handler] (/app/.next/server/pages/_middleware.js:1396:38) 
      at adapter (/app/.next/server/pages/_middleware.js:2395:35)                                                                            
      at Module.__WEBPACK_DEFAULT_EXPORT__ (/app/.next/server/pages/_middleware.js:36:96)         
      at Object.run (/app/node_modules/next/dist/server/web/sandbox/sandbox.js:29:65)
      at NextNodeServer.runMiddleware (/app/node_modules/next/dist/server/next-server.js:842:46) {
    input: '/dashboard',
    code: 'ERR_INVALID_URL'
  }
}
react-i18next:: You will need to pass in an i18next instance by using initReactI18next
Error: URLs is malformed. Please use only absolute URLs - https://nextjs.org/docs/messages/middleware-relative-urls
    at Object.validateURL (/app/.next/server/pages/_middleware.js:3065:15)
    at Function.rewrite (/app/.next/server/pages/_middleware.js:2908:53)
    ... 4 lines matching cause stack trace ...
    at NextNodeServer.runMiddleware (/app/node_modules/next/dist/server/next-server.js:842:46)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.fn (/app/node_modules/next/dist/server/next-server.js:691:30)
    at async Router.execute (/app/node_modules/next/dist/server/router.js:228:32) {
  [cause]: TypeError [ERR_INVALID_URL]: Invalid URL
      at new NodeError (node:internal/errors:372:5)
      at onParseError (node:internal/url:563:9)
      at new URL (node:internal/url:643:5)
      at Object.validateURL (/app/.next/server/pages/_middleware.js:3063:23)
      at Function.rewrite (/app/.next/server/pages/_middleware.js:2908:53)
      at Object.middleware [as handler] (/app/.next/server/pages/_middleware.js:1396:38)
      at adapter (/app/.next/server/pages/_middleware.js:2395:35)
      at Module.__WEBPACK_DEFAULT_EXPORT__ (/app/.next/server/pages/_middleware.js:36:96)
      at Object.run (/app/node_modules/next/dist/server/web/sandbox/sandbox.js:29:65)
      at NextNodeServer.runMiddleware (/app/node_modules/next/dist/server/next-server.js:842:46) {
    input: '/dashboard',
    code: 'ERR_INVALID_URL'
  }
}
```

**Comment by aapeliv** [comment]
@lucaslcode @darrenvong
